export const ADD_PRODUCT = 'ADD_PRODUCT';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const REMOVE_ALL_THIS_PRODUCT = 'REMOVE_ALL_THIS_PRODUCT';
export const LOAD_FROM_STORE = 'LOAD_FROM_STORE';
export const CLEAR_ALL_PRODUCTS = 'CLEAR_ALL_PRODUCTS';

export const SET_TOKEN = 'SET_TOKEN';

export const SET_SHOP = 'SET_SHOP';

export const SET_SELECTED_SHOP = 'SET_SELECTED_SHOP'

export const SET_CITY = 'SET_CITY';

export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';
export const ADD_SEARCH_VALUE_TO_HISTORY = 'ADD_SEARCH_VALUE_TO_HISTORY';
export const CLEAR_SEARCH_HISTORY = 'CLEAR_SEARCH_HISTORY';